services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tms
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: tms_password
    command: ["postgres", "-p", "55432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "55432:55432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tms_user -d tms -p 55432"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build: ./server
    restart: always
    environment:
      - GIT_TOKEN=${GIT_TOKEN}
      - DB_HOST=postgres
      - DB_PORT=55432
      - DB_USER=tms_user
      - DB_PASSWORD=tms_password
      - DB_NAME=tms
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "8080:80"

volumes:
  postgres_data: 